### ISSUE TITLE
Dictionary issue

### ISSUE THREAD

**Issue by MysteryPancake** [prosodylab/Prosodylab-Aligner#68]
Hi! I just downloaded your aligner to test it out, and I've come across a few dictionary issues.

The first problem I encountered is that it appears many basic words are missing from the default dictionary, such as `AIN'T`, `THAT'S`, and `YOU'LL`.

I guess the default dictionary is for basic tests, so I tried [the dictionary from the dictionary repository](https://github.com/prosodylab/prosodylab.dictionaries/blob/master/en.dict). Sadly these words are still missing.

[I tried another dictionary, this time from CMUSphinx](https://github.com/cmusphinx/cmudict/blob/master/cmudict.dict). This one has a lot more words, but it gave me a few errors because of some `#` comments in the file.

I removed these comments, but then it gave me another error of the word 's' being out of order. I tried to sort it with sort.py, but this made no difference.

I'd really appreciate finding a working dictionary with more words in it, including acronyms such as the ones mentioned above. Trying to fix the CMUSphinx dictionary would also be fantastic.

Thank you for this software and any help with this!

**Comment by kylebgorman** [comment]
The dictionary distributed here is just a trivial fork of the classic CMU
one. We're not really in the pronunciation dictionary business. Why don't
you just add those words to the dictionary locally?

IMO 'S should be tokenized separately, as a single word, since it can
attach to literally any category of word in English:

[Peter]'s mother
[The Queen of England]'s corgis
[The woman I saw yesterday]'s new hat
[The man you like]'s best friend

etc.

If you don't do it this way you will (slowly, inefficiently) have to add an
"'S" form of the entire lexicon.

You may want to make sure you don't have "smart" apostrophes---I'm not sure
the underlying HTK library takes kindly to those with respect to sort order.

**Comment by kylebgorman** [comment]
Acronyms are a whole open class, so they're not usually done in the
pronunciation dictionary.

They can be read as words ("NATO"), letter sequences ("USA"), specialzied
versions thereof ("NAACP") and occasionally as the full form (if I see
"SRY" I might read it as "sorry"). There is a bunch of literature on how to
determine which but the state of the art gives us relatively low recall,
and feels out of scope for this project.

**Comment by MysteryPancake** [comment]
Ok, thanks for the information. I didn't want to add the words myself because those are only a few examples out of the many, many words I would like to recognize. It'd take me longer than my lifetime to add the rest of the English language to the dictionary without using a model.
