### ISSUE TITLE
TextGrid alignments

### ISSUE THREAD

**Issue by rolandomunoz** [prosodylab/Prosodylab-Aligner#80]
I have a few thousand words aligned in TextGrid files. Is there a way to use these files as input for segment alignment? I mean, using the time boundaries as the start and end for the first and last segment, instead of creating TextGrid files from the scratch.

Thank you!

**Comment by kylebgorman** [comment]
No, there's no easy way to exploit word-aligned data. First, the model
works at the phones level anyways so that's not enough information even to
initialize the model informatively; secondly, there's no easy way to feed
it phone information.

Just train it at the utterance level instead, using the `-t` flag. It
almost always works.
